#
# Makefile
# 

CC = gcc

# CAUTION: Always use '-pthread' when compiling POSIX threads-based
# applications, instead of linking with "-lpthread" directly.
CFLAGS = -Wall -O2 -pthread

all: pthread-test simplesync-mutex simplesync-atomic kgarten mandel mandel_sema mandel_cond

## Pthread test
pthread-test: pthread-test.o
	$(CC) $(CFLAGS) -o pthread-test pthread-test.o $(LIBS)

pthread-test.o: pthread-test.c
	$(CC) $(CFLAGS) -c -o pthread-test.o pthread-test.c

## Simple sync (two versions)
simplesync-mutex: simplesync-mutex.o
	$(CC) $(CFLAGS) -o simplesync-mutex simplesync-mutex.o $(LIBS)

simplesync-atomic: simplesync-atomic.o
	$(CC) $(CFLAGS) -o simplesync-atomic simplesync-atomic.o $(LIBS)

simplesync-mutex.o: simplesync.c
	$(CC) $(CFLAGS) -DSYNC_MUTEX -c -o simplesync-mutex.o simplesync.c

simplesync-atomic.o: simplesync.c
	$(CC) $(CFLAGS) -DSYNC_ATOMIC -c -o simplesync-atomic.o simplesync.c

## Kindergarten
kgarten: kgarten.o
	$(CC) $(CFLAGS) -o kgarten kgarten.o $(LIBS)

kgarten.o: kgarten.c
	$(CC) $(CFLAGS) -c -o kgarten.o kgarten.c


## Mandel
mandel: mandel-lib.o mandel.o
	$(CC) $(CFLAGS) -o mandel mandel-lib.o mandel.o $(LIBS)

mandel-lib.o: mandel-lib.h mandel-lib.c
	$(CC) $(CFLAGS) -c -o mandel-lib.o mandel-lib.c $(LIBS)

mandel.o: mandel.c
	$(CC) $(CFLAGS) -c -o mandel.o mandel.c $(LIBS)

## Mandel_Sema
mandel_sema: mandel-lib.o mandel_sema.o
	$(CC) $(CFLAGS) -o mandel_sema mandel-lib.o mandel_sema.o $(LIBS)

mandel_sema.o: mandel_sema.c
	$(CC) $(CFLAGS) -c -o mandel_sema.o mandel_sema.c $(LIBS)

## Mandel_Cond
mandel_cond: mandel-lib.o mandel_cond.o
	$(CC) $(CFLAGS) -o mandel_cond mandel-lib.o mandel_cond.o $(LIBS)

mandel_cond.o: mandel_cond.c
	$(CC) $(CFLAGS) -c -o mandel_cond.o mandel_cond.c $(LIBS)
clean:
	rm -f *.s *.o pthread-test simplesync-* kgarten mandel mandel_sema mandel_cond 
